---
- name: Install Helm and configure Nexus
  hosts: k8s
  become: false
  environment:
    KUBECONFIG: "/home/gitlab-runner/.kube/config"
    PATH: "/home/gitlab-runner/.local/bin:/usr/local/bin:/usr/bin:/bin"
  roles:
    - helm
    - nexus
