apiVersion: v1
kind: ConfigMap
metadata:
  name: toystore-config
  namespace: {{ .Values.namespace }}
data:
  DB_HOST: "{{ .Values.mysqlServiceName }}.{{ .Values.namespace }}.svc.cluster.local"
  DB_PORT: "3306"
  DB_NAME: "{{ .Values.dbName }}"
